import type { IconType } from 'react-icons'
import {
  FaBell,
  FaBox,
  FaChartLine,
  FaClipboardList,
  FaDollarSign,
  FaEnvelope,
  FaFileInvoice,
  FaFileInvoiceDollar,
  FaHistory,
  FaHome,
  FaMoneyBillWave,
  FaShoppingCart,
  FaStore,
  FaUserCircle,
  FaUserShield,
  FaUserTie,
  FaUsers,
  FaUtensils,
  FaWarehouse,
} from 'react-icons/fa'
import type { IconKey } from '@/constants/menu'

export const MENU_ICON_MAP: Record<IconKey, IconType> = {
  dashboard: FaHome,
  alerts: FaBell,
  customers: FaUsers,
  menu: FaUtensils,
  orders: FaShoppingCart,
  history: FaHistory,
  planner: FaChartLine,
  bills: FaFileInvoiceDollar,
  expenses: FaMoneyBillWave,
  store: FaStore,
  outstanding: FaDollarSign,
  workforce: FaUserTie,
  analytics: FaChartLine,
  tax: FaFileInvoice,
  stock: FaBox,
  inventory: FaWarehouse,
  users: FaUserShield,
  audit: FaClipboardList,
  enquiries: FaEnvelope,
  profile: FaUserCircle,
}
